### ISSUE TITLE
Signal: Help button, with support message

### ISSUE THREAD

**Issue by MisterChalmers** [chalmersproject/chalmers-signal-occupancy#2]
set dial button as a support button
- if you hold down button for 5 seconds a special page comes up that says "SENDING FOR SUPPORT IN 5...4....3...2..1.."
	- then it sends chalmersproject a telegram message or something with the shelter name that asked for help

diagram on chalmers signal explaining you can hold down dial to send a HELP! SUPPORT message to chalmersproject

---

i've created a GuiSlice Page to trigger when button is pressed.
I'm creating an interrupt for when button is pressed.

added this to setup and also this interrupt

```cpp

void ICACHE_RAM_ATTR encoder_button_trigger()
{
  encoder_button_pressed = true;
  Serial.println("encoder button pressed!");
}

//...

void setup()
{
//...
attachInterrupt(digitalPinToInterrupt(5), encoder_button_trigger, ONLOW);
//...
}

**Comment by MisterChalmers** [comment]
With commit https://github.com/chalmersproject/chalmers-signal-occupancy/commit/171332c4b4eff65d069a7629202d870bbf063675 signal now triggers "call for help screen with rotary encoder button is pressed.

## WIP items

- [x] send telegram message
- [ ] add a "sending support message" screen
- [ ] add a "support message sent!" screen

**Comment by MisterChalmers** [comment]
signal telegram butotn now actually sends a message to a telegram support group. https://github.com/chalmersproject/chalmers-signal-occupancy/commit/83694a6500fe19272a4811ecea47b05dc932dd6f

## TODO: 

- [x] pull sheltername from API and sub that name into the support message sent to telegram
- [ ] add "sending telegram message, telegram message sent!" screens.
- [ ] add error handling for telegram API and display error on screen
- [x] add logo to chalmers signal bot

**Comment by MisterChalmers** [comment]
opened PR with addition screens for message sending/message sent and refactor of handle_button function https://github.com/chalmersproject/chalmers-signal-occupancy/pull/3

**Comment by MisterChalmers** [comment]
This feature is complete! Some to have improvements for this feature for later:

- [ ] send phone number for shelter in telegram support message. Something like:
```
St. Felix Augusta's Spot Signal: NEED HELP!
Phone: (123) 213 2134
Address: 444 real address street, fake land
```

- [ ] add confirmation screen to GUISLICE for telling user 

```
support message sent!
someone will call or be by to help shortly
```
